### PR TITLE
3 add husky

### PR DESCRIPTION
**Pull request by jasonzhwang**
# add husky to the existing project
# run lint before husky pre-commit, prettier and test will be added in the coming PRs

### CODE REVIEW

**Review by tatoMa — COMMENTED** [review]
I dont think husky runs on every commit. Please check it on your computer to show the prove of running husky.js.

Something like this:
image

**Comment by jasonzhwang** [comment]
Hi,

This is the proof of running husky on my local computer.

image

As shown above, it will run Eslint before committing,  but it failed if the message is without a commit type. After the type"fix" is added, it passes the commit lint restriction. And being able to push the code to the repository as below.

image


Cheers,

Jason

**Comment by Double-Twelve** [comment]
1. you should add `"prepare": "husky install"` script in `package.json`, so that when someone pull the code, he/she run `npm i`, and this will automatically trigger this script.

2. image
This commit is what I use for testing, you can change it back or leave it alone.

**Comment by jasonzhwang** [comment]
> * you should add `"prepare": "husky install"` script in `package.json`, so that when someone pull the code, he/she run `npm i`, and this will automatically trigger this script.
> * image
>   This commit is what I use for testing, you can change it back or leave it alone.




Hi Double-Twelve,

I have already added on the "prepare script" for husky.

Now should be alright when users pull and run the husky. Thanks for you mentoring.

Cheers

**Review by Double-Twelve — APPROVED** [review]

**Pull request merged**
