### PR TITLE
Init project repo

### PR DESCRIPTION
**Pull request by Eric-ZheranLi**
In this next app initialization, Typescript, ESLint, App Router are used in the project, while Tailwind CSS and 'src/' directory not.

Engine locking is used in package.json to require node version >=16, npm version >=8, and yarn is forbidden(only npm).

### CODE REVIEW

**Review by tatoMa — APPROVED** [review]
LGTM

**Review by Trent1900 — APPROVED** [review]
LGTM.
BTW, do we want to use Husky?

**Comment by Prom1s1ngYoung** [comment]
LGTM

**Comment by tatoMa** [comment]
> 

Yes, we will add Husky on the other card. #3 if I'm not wrong.

**Comment by Eric-ZheranLi** [comment]
Sorry, I forget to connect this pull request with issue before merging... I will remember to do it next time.

Is it ok I manually close the corresponding issue?

**Pull request merged**
