### PR TITLE
26 create the main section of audio call page 1

### PR DESCRIPTION
**Pull request by jasonzhwang**
implemented audio call page 1, will totally refactor to tailwind later
Screenshot 2023-06-29 at 11 50 41 am
while hovered:
Screenshot 2023-06-29 at 11 50 47 am
while active:
Screenshot 2023-06-29 at 11 52 53 am

### CODE REVIEW

**Comment by Double-Twelve** [comment]
your PR is very similar to another one(https://github.com/taodemy/taotalk/pull/50), maybe you guys should discuss it, and then extract the same part into a component to avoid duplication of code

**Comment by jasonzhwang** [comment]
> your PR is very similar to another one(#50), maybe you guys should discuss it, and then extract the same part into a component to avoid duplication of code

Hi Shawn, 

Yes it is. (#50) and (#59) are very similar ticket and literally can extracted as one component. I believe that Boss Tao seperate it as two tickets because he may want us to open another refactoring ticket later so that someone may be interested in trying to extract components from replicate code.

**Comment by Eric-ZheranLi** [comment]
> > your PR is very similar to another one(#50), maybe you guys should discuss it, and then extract the same part into a component to avoid duplication of code
> 
> Hi Shawn,
> 
> Yes it is. (#50) and (#59) are very similar ticket and literally can extracted as one component. I believe that Boss Tao seperate it as two tickets because he may want us to open another refactoring ticket later so that someone may be interested in trying to extract components from replicate code.

I made some other implementation because I am wating for the final version of the outlined button. I will refactor the similar one(#50) after the merging of this branch.

**Review by Eric-ZheranLi — APPROVED** [review]
Looks good to me.

**Pull request merged**
